services:
  docs:
    image: central_blood_bank_local_docs
    container_name: central_blood_bank_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./central_blood_bank:/app/central_blood_bank:z
    ports:
      - '9000:9000'
    command: /start-docs
