# Generated by Django 5.1.8 on 2025-04-10 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donor',
            options={'ordering': ['-id'], 'verbose_name': 'Donor', 'verbose_name_plural': 'Donors'},
        ),
    ]
