# Generated by Django 5.1.8 on 2025-04-10 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0003_alter_donor_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodstock',
            name='city',
            field=models.CharField(choices=[('Cairo', 'Cairo'), ('Mansoura', 'Mansoura'), ('Tanta', 'Tanta'), ('Alexandria', 'Alexandria'), ('Zagazig', 'Zagazig'), ('Benha', 'Benha'), ('Damietta', 'Damietta'), ('Ismailia', 'Ismailia'), ('Suez', 'Suez'), ('Port Said', 'Port Said')], max_length=50),
        ),
    ]
