# Generated by Django 5.1.8 on 2025-04-10 13:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_requests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitalrequest',
            name='email',
            field=models.EmailField(default='', max_length=254, validators=[django.core.validators.EmailValidator()]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hospitalrequest',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='hospitalrequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Uncompleted', 'Uncompleted')], default='Pending', max_length=12),
        ),
    ]
