# Generated by Django 5.1.8 on 2025-04-07 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_requests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_name', models.CharField(max_length=100)),
                ('blood_type', models.CharField(max_length=3)),
                ('city', models.CharField(max_length=50)),
                ('urgency_level', models.CharField(choices=[('Immediate', 'Immediate'), ('Urgent', 'Urgent'), ('Normal', 'Normal')], max_length=10)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='bloodstock',
            name='donor',
        ),
        migrations.DeleteModel(
            name='Donor',
        ),
        migrations.DeleteModel(
            name='BloodStock',
        ),
    ]
